server:
  port: 8765

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#eureka:
#  instance:
#    hostname: discovery-prod-df66734906f8.herokuapp.com
#  client:
#    serviceUrl:
#      defaultZone: https://discovery-prod-df66734906f8.herokuapp.com/eureka/

zuul:
#  prefix: /api
#  ignored-services: "*"
  
  routes: 
    CrudService:
      service-id: CrudService
      path: /crudservice/**
