server:
  port: 8083
  servlet:
    context-path: /authService
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  application:
    name: authService
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      id:
        new_generator_mappings: false
  rabbitmq:
    host:  localhost
    port: 5672
    username: admin
    password: admin

eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8087/discovery/eureka

auth:
  rabbitmq:
    exchange: auth.exchange
    routingKeySignup: auth.signup.routingKey

security:
  jwt:
    token:
      secret_key: key_microservices
      expire_time: 300000 # 5 minutos 

UserController:
  signin: Autentica usuário e retorna seu token JWT.
  signup: Cria usuário e retorna seu token JWT
  delete: Apaga usuário específico de acordo com ID
  search: Retorna usuário específico de acordo com ID
  me: Retorna dados do usuário atual
  refresh: Reinicia o tempo do token JWT