server:
  port: 8083
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: admin
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      id:
        new_generator_mappings: false

eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

security:
  jwt:
    token:
      secret_key: key_microservices
      expire_time: 300000 # 5 minutos 

UserController:
  signin: Autentica usuário e retorna seu token JWT.
  signup: Cria usuário e retorna seu token JWT
  delete: Apaga usuário específico de acordo com ID
  search: Retorna usuário específico de acordo com ID
  me: Retorna dados do usuário atual