server:
  port: 8083
  servlet:
    context-path: /auth
    
spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: admin

eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

security:
  jwt:
    token:
      secret_key: key_microservices
      expire_time: 360000
  