version: '3.1'
services:
  app:
    container_name: rent_service
    image: rent_service
    build: ./
    ports:
      - "8087:8087"
    depends_on:
      #- discovery
      #- gateway
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db_rent
  #discovery:
    #image: matt0balda/imovato:discovery
    #ports:
     # - "8087:8087"
      #- "8085:8085"
  #gateway:
    #image: matt0balda/imovato:gateway
    #ports:
     # - "8087:8087"
     # - "8085:8085"