server:
  port: 8082
  servlet:
    context-path: /paymentService
    
spring:
  application:
    name: paymentService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  rabbitmq:
    host:  localhost
    port: 5672
    username: admin
    password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.property.queue

eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka
  