server:
  port: 8085
  servlet:
    context-path: /rentService
    
spring:
  application:
    name: rentService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/rent?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

  rabbitmq:
    host:  localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.rent.property
    queueUser: crud.rent.user

eureka:
  instance:
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8087/discovery/eureka
  