server:
  port: ${PORT}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80
