# SONAR LOCAL: mvn clean verify sonar:sonar -Dsonar.projectKey=Imovato -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_8065f01e13e240636a05812095cc3af86e62507c
server:
  port: 8081
  servlet:
    context-path:

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/crud-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: example

  data:
    mongodb:
      host: localhost
      port: 27017
      database: crud-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkeyProperty: crud.property.routingkey
    routingkeyUser: crud.user.routingkey
    authExchange: auth.exchange
    signupQueue: auth.signup

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
