# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-microservices:
    name: Build Microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: ['discovery', 'gateway', 'scheduling', 'acquisition', 'CrudService', 'auth', 'payment', 'rent']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Docker
      run: docker-compose up -d
    - name: Compile code
      run: cd ${{ matrix.microservice }} && mvn compile
    - name: Run tests
      run: cd ${{ matrix.microservice }} && mvn test
