# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ develop ]

jobs:
  scheduling:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: scheduling
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile code
      run: mvn compile
    - name: Run tests
      run: mvn test
